# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NecMinSR
                                 A QGIS plugin
 software to support eutrophication level detection
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-30
        copyright            : (C) 2024 by Eric Costa
        email                : jefc21@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NecMinSR class from file NecMinSR.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .eutrophication import NecMinSR
    return NecMinSR(iface)
