# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NecMinSR
                                 A QGIS plugin
 software to support eutrophication level detection
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-04-30
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Eric Costa
        email                : jefc21@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QComboBox
from qgis.core import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .eutrophication_dialog import NecMinSRDialog
import os.path



class NecMinSR:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        path_output=""
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'NecMinSR_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&NEC_MinSR')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('NecMinSR', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """
        self.dlg = NecMinSRDialog()

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/eutrophication/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'NEC_MinSR'),
            callback=self.run,
            parent=self.iface.mainWindow())

        #adicionar saída
        self.dlg.label_output.clear() 
        self.dlg.bt_output.clicked.connect(self.path_out)

        #atualiza lista de layers
        self.dlg.bt_update.clicked.connect(self.update_layers)

        #seleciona banda verde
        self.dlg.band_green.clear()
        self.dlg.band_green.currentIndexChanged.connect(self.select_band_green)

        #seleciona banda blue
        self.dlg.band_blue.clear()
        self.dlg.band_blue.currentIndexChanged.connect(self.select_band_blue)

        #seleciona banda red
        self.dlg.band_red.clear()
        self.dlg.band_red.currentIndexChanged.connect(self.select_band_red)

        #seleciona banda mid
        self.dlg.band_mid.clear()
        self.dlg.band_mid.currentIndexChanged.connect(self.select_band_mid)

        #seleciona banda mear
        self.dlg.band_mear.clear()
        self.dlg.band_mear.currentIndexChanged.connect(self.select_band_mear)

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&NEC_MinSR'),
                action)
            self.iface.removeToolBarIcon(action)

    def path_out(self):
        global path
        global path_output
        path = QFileDialog.getSaveFileName(self.dlg, "Salvar o   arquivo em: ", "", "*.TIF"),
        path_output=path[0][0]
        self.dlg.label_output.setText(path_output)

    def update_layers(self):
        a=QgsProject.instance()
        layers_names=[]
        global layers_source
        layers_source=[]

        for layer in a.mapLayers().values():
            layers_names.append(layer.name())
            layers_source.append(layer.source())
        if(len(layers_names)>0):
            self.dlg.band_green.clear()
            self.dlg.band_blue.clear()
            self.dlg.band_red.clear()
            self.dlg.band_mid.clear()
            self.dlg.band_mear.clear()
            self.dlg.band_green.addItems(layers_names)
            self.dlg.band_blue.addItems(layers_names)
            self.dlg.band_red.addItems(layers_names)
            self.dlg.band_mid.addItems(layers_names)
            self.dlg.band_mear.addItems(layers_names)

    def select_band_green(self): 
        if(len(layers_source)>0):
            selectedLayerIndex = self.dlg.band_green.currentIndex()
            global layers_source_green
            layers_source_green=layers_source[selectedLayerIndex].replace( '\\' , '/')
            self.dlg.lineEdit_green.setText(layers_source_green)
            self.dlg.label_green.setText(layers_source_green)

    def select_band_blue(self): 
        if(len(layers_source)>0):
            selectedLayerIndex = self.dlg.band_blue.currentIndex()
            global layers_source_blue
            layers_source_blue=layers_source[selectedLayerIndex].replace( '\\' , '/')
            self.dlg.lineEdit_blue.setText(layers_source_blue)
            self.dlg.label_blue.setText(layers_source_blue)

    def select_band_red(self): 
        if(len(layers_source)>0):
            selectedLayerIndex = self.dlg.band_red.currentIndex()
            global layers_source_red
            layers_source_red=layers_source[selectedLayerIndex].replace( '\\' , '/')
            self.dlg.lineEdit_red.setText(layers_source_red)
            self.dlg.label_red.setText(layers_source_red)

    def select_band_mid(self): 
        if(len(layers_source)>0):
            selectedLayerIndex = self.dlg.band_mid.currentIndex()
            global layers_source_mid
            layers_source_mid=layers_source[selectedLayerIndex].replace( '\\' , '/')
            self.dlg.lineEdit_mid.setText(layers_source_mid)
            self.dlg.label_mid.setText(layers_source_mid)

    def select_band_mear(self): 
        if(len(layers_source)>0):
            selectedLayerIndex = self.dlg.band_mear.currentIndex()
            global layers_source_mear
            layers_source_mear=layers_source[selectedLayerIndex].replace( '\\' , '/')
            self.dlg.lineEdit_mear.setText(layers_source_mear)
            self.dlg.label_mear.setText(layers_source_mear)
           
           

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        #if self.first_start == True:
        #    self.first_start = False
        #    self.dlg = NecMinSRDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
